### ISSUE TITLE
Install Treeio on Heroku or Openshift ?

### ISSUE THREAD

**Issue by hideadesign** [treeio/treeio#100]
Hello

Is there a guide to install Treeio on Heroku or Openshift ? That would be awesome !

Thanks :)

**Comment by tovmeod** [comment]
it should be no different than installing any other django project and confguring the database.

sorry but I don't have much experience with Heroku or Openshift, if you did manage please post here or a link to your blog post explaining how so we can close the issue.

If you have the time we would gladly accept a how to to be included in the documentation we are preparing
