### ISSUE TITLE
Need GOOD documentation manuals (electronic or PDF).

### ISSUE THREAD

**Issue by FarmerTom0** [treeio/treeio#105]
There need to be:
1) a good installation manual
2) users manual
3) sys admin manual

I'm willing to write them as I go but any insight from others would be greatly appreciated.

**Comment by tovmeod** [comment]
@FarmerTom0 did you write the manual? could you contribute to the project documentation?

**Comment by FarmerTom0** [comment]
We ran into too many issues and abandoned treeIO.  We're using Redmine 
and have have few issues (once we got it running which DID have issues).

Thank You,
Tom Neff

**Comment by rogeriofalcone** [comment]
We are working on the issues of Tree.io.

We are working on the installation script for fast installation, even for people without linux domain.

If you want to cooperate with the Tree.io design, please send an email to rogerio@falconeit.com.br
Thank you

**Comment by rogeriofalcone** [comment]
​
 evergreen.zip
<https://docs.google.com/file/d/0B4WBI1butHzhYWt2SEZ2YkJOdlk/edit?usp=drive_web>
​site  em anexo

>
