### ISSUE TITLE
custom plugin template does not loaded.

### ISSUE THREAD

**Issue by cadu-leite** [treeio/treeio#150]
When customized a template inside a new app (plugin) the changes are not seen on the app. 

All the treeio project templates are aoutside their apps, in a base dir (on settings.py). 

When a new app has a custom template, it has no chance to be loaded because without manually create ou customize the original template. 

settings.py

```
'django.template.loaders.filesystem.Loader',
'django.template.loaders.app_directories.Loader',
'django.template.loaders.filesystem.Loader',
'django.template.loaders.eggs.Loader',
```

So, if the django find the template on filesystem, it stop (default behavior) 
I suggest to swap the order of template_loaders, I believe the impact will be minor.

Path schema of my trying 
.
├── bin
...
├── git_hook
│   ├── migrations
│   └── templates
│       └── html
│           └── account  
│                       └── account_view.hmtl  <<< thats the CUSTOM template
...
├── templates
│   ├── html
│   │   ├── account
│   │   │   └── tags
│                       └── account_view.hmtl  <<< thats the ORIGINAL template
... ... ... ...
├── treeio
│   ├── account                                     <<<  Aplication with no templates
│   │   ├── south_migrations
│   │   └── templatetags
... ... ... 
└── treeio_project

**Comment by tovmeod** [comment]
Keep in mind that you don't need to use the settings provided, you can use it just as an example.
In any case I'm accepting the PR, thanks for the contribution.
