### ISSUE TITLE
change mimetype to content_type

### ISSUE THREAD

**Issue by tovmeod** [treeio/treeio#154]
/treeio/treeio/core/views.py:187
/treeio/treeio/core/decorators.py:132

https://github.com/treeio/treeio/search?utf8=%E2%9C%93&q=mimetype

**Comment by macedd** [comment]
Yes it worked, could not find any other problem regarding django 1.7..
I have published the container: `docker pull thiagof/treeio`

**Comment by tovmeod** [comment]
thanks for reporting the bug!
