### ISSUE TITLE
You're using the staticfiles app without having set the STATIC_ROOT setting

### ISSUE THREAD

**Issue by sihorton** [treeio/treeio#48]
I just downloaded the static file for this project and extracted it and then ran the commands it told me to run to setup the virtual environment. Then it crashes out with the following error:

raise ImproperlyConfigured("You're using the staticfiles app " 
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting.

I can add STATIC_ROOT to settings.py but what value should it have?

**Comment by Otumian-empire** [comment]
Thanks though.. Your solution solved mine with
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = os.path.join(BASE_DIR, 'static')
