### ISSUE TITLE
Problems integrating tree.io with LDAP

### ISSUE THREAD

**Issue by ashkang** [treeio/treeio#99]
User authentication is now working using django-auth-ldap, however as it seems Django won't create profiles for users upon user creation. It would have been nice if things were working somehow out of the box. What I'm currenty getting upon user login is:
[error] Django user foobar does not have a profile to populate

None of the solutions posted online are working for me or I have no idea how to get them to work since I have no prior knowledge of neither Python nor Django. Tree.io Documentation does not have a step-by-step general guide on how to do this and in my humble opinion, that's a shortcoming OR do I miss something really huge here?

**Comment by tovmeod** [comment]
currently the code has a post save signal on the auth.user model creating a profile, meaning it will create a profile when creating a new user. please test with the 2.0 branch.

let me know if you still need any help or is having any issues, otherwise I'm closing the ticket
